name: ds
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2021.11
  - _pytorch_select=0.1
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.9.0
  - anaconda-project=0.10.2
  - aniso8601=9.0.1
  - anyio=2.2.0
  - appdirs=1.4.4
  - applaunchservices=0.2.1
  - appnope=0.1.2
  - appscript=1.1.2
  - argcomplete=1.12.3
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - asn1crypto=1.4.0
  - astor=0.8.1
  - astroid=2.6.6
  - async-timeout=4.0.1
  - async_generator=1.10
  - asynctest=0.13.0
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - audioread=2.1.9
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - bitarray=2.3.5
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boto=2.49.0
  - boto3=1.20.24
  - botocore=1.23.24
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cached-property=1.5.2
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=3.470
  - cftime=1.5.1.1
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.12.0
  - conda-content-trust=0.1.1
  - conda-pack=0.6.0
  - conda-package-handling=1.7.3
  - conda-token=0.3.0
  - contextlib2=0.6.0.post1
  - cookiecutter=1.7.2
  - cryptography=36.0.0
  - curl=7.80.0
  - cycler=0.11.0
  - cython=0.29.25
  - cytoolz=0.11.0
  - daal4py=2021.4.0
  - dal=2021.4.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.4
  - distributed=2021.10.0
  - docutils=0.17.1
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - expat=2.4.1
  - fastcache=1.1.0
  - fasttext=0.9.2
  - ffmpeg=4.3.2
  - filelock=3.4.2
  - flake8=3.9.2
  - flask=1.1.2
  - flask-cors=3.0.10
  - flask-restful=0.3.8
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - fsspec=2022.1.0
  - future=0.18.2
  - gast=0.2.2
  - gensim=3.8.3
  - get_terminal_size=1.0.0
  - gettext=0.21.0
  - gevent=21.8.0
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.0.8
  - gnutls=3.6.13
  - google-api-core=1.25.1
  - google-auth=1.33.0
  - google-cloud-core=1.7.1
  - google-cloud-storage=1.41.0
  - google-crc32c=1.1.2
  - google-pasta=0.2.0
  - google-resumable-media=1.3.1
  - googleapis-common-protos=1.53.0
  - greenlet=1.1.1
  - grpcio=1.42.0
  - gunicorn=20.1.0
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.3.0
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - keyring=23.4.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcrc32c=1.1.1
  - libcurl=7.80.0
  - libcxx=13.0.1
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libflac=1.3.4
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblief=0.10.1
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnetcdf=4.7.3
  - libnghttp2=1.46.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - librosa=0.9.1
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvm-openmp=12.0.0
  - llvmlite=0.36.0
  - locket=0.2.1
  - lxml=4.7.1
  - lz4-c=1.9.3
  - lzo=2.10
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - mock=4.0.3
  - more-itertools=8.12.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - multidict=5.2.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - netcdf4=1.5.3
  - nettle=3.6
  - networkx=2.6.3
  - ninja=1.10.2
  - nltk=3.6.5
  - nose=1.3.7
  - notebook=6.4.6
  - numba=0.53.0
  - numexpr=2.8.0
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1o
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - path=16.2.0
  - path.py=12.5.0
  - pathlib2=2.3.6
  - pathspec=0.7.0
  - patsy=0.5.2
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.2
  - pkginfo=1.8.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.6.0
  - poyo=0.5.0
  - prometheus_client=0.12.0
  - promise=2.3
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.19.1
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11=2.9.1
  - pybind11-global=2.9.1
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycrypto=2.6.1
  - pycurl=7.44.1
  - pydocstyle=6.1.1
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pyodbc=4.0.32
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - pytables=3.6.1
  - pytest=6.2.5
  - python=3.7.11
  - python-dateutil=2.8.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python.app=3
  - python_abi=3.7
  - pytorch=1.3.1
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1.2
  - regex=2021.11.2
  - requests=2.27.1
  - resampy=0.2.2
  - ripgrep=12.1.1
  - rope=0.21.1
  - rsa=4.7.2
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - s3transfer=0.5.0
  - scikit-image=0.18.3
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2021.4.0
  - scipy=1.6.2
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - simplegeneric=0.8.1
  - singledispatch=3.7.0
  - sip=4.19.8
  - six=1.16.0
  - smart_open=5.1.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.2.0
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlalchemy=1.4.27
  - sqlite=3.37.0
  - statsmodels=0.13.2
  - sympy=1.9
  - tbb=2021.5.0
  - tbb4py=2021.5.0
  - tblib=1.7.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-datasets=1.2.0
  - tensorflow-estimator=2.0.0
  - tensorflow-metadata=0.14.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss=0.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - torchvision=0.4.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - ujson=4.2.0
  - unicodecsv=0.14.1
  - unidecode=1.2.0
  - unixodbc=2.3.9
  - urllib3=1.26.7
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.1
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=3.0.2
  - x264=1!161.3030
  - xlrd=2.0.1
  - xlsxwriter=3.0.2
  - xlwings=0.24.9
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.5.1
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - astropy==4.3.post1
    - numpy==1.18.0
    - pyerfa==1.7.2
